### ISSUE TITLE
Request: Don't use the word "connector"

### ISSUE THREAD

**Issue by dstillman** [vanakat/zotero-bridge#7]
Just a small request: please don't use the word "connector" to refer to integration plugins or similar tools. "Connector" has a specific meaning in Zotero — the Zotero Connector has been the official name of the <a href="https://www.zotero.org/download/">browser extensions that save to Zotero</a> for over a decade. That's what Zotero users expect when they hear that term, so calling other things "connectors" is likely to be very confusing, both in discussions and search results. We made a similar request to the developer of the other Obsidian plugin, who has since changed the name.

(To clarify, the file in Zotero is called server_connector.js because it defines the Zotero.Server endpoints for the Zotero Connector. Other endpoints would be…for things other than the Connector.)

**Comment by MunGell** [comment]
This is now addressed in v1.2.3 of the plugin

**Comment by dstillman** [comment]
Thank you!
